[workspace]
members = [
    ".",
    "generator"
]

[package]
name = "pugl-sys"
version = "0.1.0"
edition = "2024"

[features]
opengl = []
vulkan = []
cairo = []

[[example]]
name = "example"
required-features = ["opengl"]