[package]
name = "pugl-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
pugl-rs-sys = { path = "../pugl-rs-sys" }
bitflags = "2.8"

[features]
opengl = ["pugl-rs-sys/opengl"]

[[example]]
name = "opengl"
required-features = ["opengl"]
